config/routes.rb
Rails.application.routes.draw do


  get 'booking/index'
# For styled pages
  root 'sessions#new'

  get 'sessions/new'
  get 'app/views/users/new.html.erb', to: 'users#new', as: 'new_user'
  get 'app/views/users/index.html.erb', to: 'users#index', as: 'show_users'
  get 'app/views/login/index.html.erb', to: 'login#index', as: 'login'
  get 'app/views/home/index.html.erb', to: 'home#index', as: 'home'
  get 'app/views/results/index.html.erb', to: 'results#index', as: 'results'
  get 'app/views/advancedsearch/index.html.erb', to: 'advancedsearch#index', as: 'advancedsearch'
  get 'app/views/browsingsearch/index.html.erb', to: 'browsingsearch#index', as: 'browsingsearch'
  get 'app/views/calendar/index.html.erb', to: 'calendar#index', as: 'calendar'
  get 'app/views/calendar_bookings/index.html.erb', to: 'calendar_bookings#index', as: 'calendar_bookings'
  get 'app/views/dailyreservations/index.html.erb', to: 'dailyreservations#index', as: 'dailyreservations'
  get 'app/views/calendar/show.html.erb', to: 'calendar#show', as: 'show_calendar'

  get    '/bright',  to: 'bright#index'
  get    '/rdmc',    to: 'rdmc#index'
  get    '/results',    to: 'results#index'

  get    '/bright',   to: 'bright#index'
  get    '/rdmc',   to: 'rdmc#index'
  get    '/add',    to: 'add#index'
  post   '/add',     to: 'rooms#create'
  get    '/delete',       to: 'delete#index'
  get    '/home',       to: 'home#index'
    
    
    
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create', as: 'login_path'
  get    '/create',  to: 'users#new'
  post   '/create',  to: 'users#create', as: 'users_path'
  delete '/logout',  to: 'sessions#destroy'
  delete '/user', to: 'users#destroy'

   resources :home
   resources :login
   resources :advancedsearch
   resources :results
   resources :browsingsearch
   resources :users, :bookings, :rooms
   resources :sessions
   resources :calendar
   resources :calendar_bookings
   
   get "*path", to: redirect('/')
end

app/controllers/bright_controller.rb
class BrightController < ApplicationController
before_action :validate_access 
  def room_params
    params.require(:Room).permit(:room_id, :roomtype, :operate_start, :operate_end)
  end

  def show
    id = params[:id] # retrieve Room ID from URI route
    @room = Room.find(id) # look up Room by unique ID
    # will render app/views/Rooms/show.<extension> by default
  end

  def index
    @rooms = Room.all
  end

  def new
    #attr_accessor :building_name, :room_id, :roomtype, :description, :booked, :booker, :operate_start, :operate_end
    def initialize(attributes = {})
      @building_name  = attributes[:building_name]
      @room_id = attributes[:room_id]
      @roomtype = attributes[:roomtype]
      @description = attributes[:description]
      @booked = attributes[:booked]
      @booker = attributes[:booker]
      @operate_start = attributes[:operate_start]
      @operate_end = attributes[:operate_end]
      
    end
  end

  def create
    @room = Room.create!(room_params)
    flash[:notice] = "#{@room.name} was successfully created."
    redirect_to rooms_path
  end

  def edit
    @room = Room.find params[:id]
  end

  def update
    @room = Room.find params[:id]
    @room.update_attributes!(Room_params)
    flash[:notice] = "#{@room.name} was successfully updated."
    redirect_to room_path(@room)
  end

  def destroy
    @Room = Room.find(params[:id])
    @Room.destroy
    flash[:notice] = "Room '#{@room.name}' deleted."
    redirect_to rooms_path
  end
  
private 
  def validate_access 
      unless logged_in?
        redirect_to root_path
      end 
  end
end

app/views/bright/index.html.erb
<!DOCTYPE HTML>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="R^2">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <title>R^2 browsing search</title>
    </head>
    
    <body>
      <%= render './layouts/nav.html.erb' %>
      <main>
        <fieldset>
          <legend>Rooms in Bright</legend>
          <div id = "map">
            <img src="/assets/BrightFloorPlans_Floor1-1.jpg" width="850" height="750" alt="HRBB_Floor_1" usemap="#HRBB_Floor_One">
            <map name="HRBB_Floor_One">
              <% current_uri = request.path_info %>
              <% room = Room.where(["building_name ? and room_id = ?", "HRBB", 124]) %>
              <% if Room.where(:id => 1).count > 0 %>
                <area shape="rect" coords="328,178,447,274" href= "<%= url_for room_path(1, :current_page => current_uri) %>" alt="126">
              <% end %>
              <% if Room.where(:id => 2).count > 0 %>
              <area shape="rect" coords="222,33,542,175" href= "<%= url_for room_path(2, :current_page => current_uri) %>" alt="124">
              <% end %>
              <% if Room.where(:id => 3).count > 0 %>
              <area shape="rect" coords="454,178,551,274" href= "<%= url_for room_path(3, :current_page => current_uri) %>" alt="129">
              <% end %>
              <% if Room.where(:id => 4).count > 0 %>
              <area shape="rect" coords="287,427,448,565" href= "<%= url_for room_path(4, :current_page => current_uri) %>" alt="113">
              <% end %>
              <% if Room.where(:id => 5).count > 0 %>
              <area shape="rect" coords="691,427,821,519" href= "<%= url_for room_path(5, :current_page => current_uri) %>" alt="104">
              <% end %>
            </map>
          </div>
           <div id = "table">
           <table>
                  <tr>
                    
                    <th>Room ID</th>
                    <th>Room Type</th>
                    
                    <th>Operate Start</th>
                    <th>Operate End</th>
                    <th>Technology</th>
                    <th>Arrangement</th>
                    <th>Number of People</th>
                  </tr>
                
                  <% @rooms.each do |room| %>
                  <%if room.building_name == 'HRBB'%>
                    <tr>
                      
                      <td><%= room.room_id %></td>
                      <td><%= room.roomtype %></td>
                      <td><%= room.operate_start.strftime("%k:%M") %></td>
                      <td><%= room.operate_end.strftime("%k:%M") %></td>
                      <td><%= room.tech %></td>
                      <td><%= room.arrangement%> </td>
                      <td><%= room.numpeople%> </td>
                    </tr>
                  <% end %>
                  <% end %>
                </table>
                </div>
                <button class ="btn" onclick="mapFunction()">Toggle Map View</button>
                <button class ="btn" onclick="tableFunction()">Toggle Table View</button>
          <%= link_to 'Back', browsingsearch_path, :class => "btn" %>
        </fieldset>
      </main>
    </body>
</html>



<script>
function mapFunction() {
  var x = document.getElementById("map");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}

function tableFunction() {
  var x = document.getElementById("table");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>

app/views/bright/index_old.html.erb
<!DOCTYPE HTML>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="R^2">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <title>R^2 browsing search</title>
    </head>
    
    <body>
      <%= render './layouts/nav.html.erb' %>
      <main>
        <fieldset>
          <legend>Rooms in Bright</legend>
          <table>
            <tr>
              <th>Room ID</th>
              <th>Room Type</th>
              
              <th>Operate Start</th>
              <th>Operate End</th>
              <th>Technology</th>
              <th>arrangement</th>
              <th>Number of People</th>
            </tr>
          
            <%@rooms.each do |room| %>
             <%if room.building_name == 'HRBB'%>
              <tr>
                
                <td><%= room.room_id %></td>
                <td><%= room.roomtype %></td>
             
                
                <td><%= room.operate_start.strftime("%k:%M") %></td>
                <td><%= room.operate_end.strftime("%k:%M") %></td>
                <td><%= room.tech %></td>
                <td><%= room.arrangement%> </td>
                <td><%= room.numpeople%> </td>
               
              </tr>
              <% end %>
            <% end %>
          </table>
          <%= link_to 'Back', :back, :class => "btn" %>
        </fieldset>
      </main>
    </body>
</html>