config/routes.rb
Rails.application.routes.draw do


  get 'booking/index'
# For styled pages
  root 'sessions#new'

  get 'sessions/new'
  get 'app/views/users/new.html.erb', to: 'users#new', as: 'new_user'
  get 'app/views/users/index.html.erb', to: 'users#index', as: 'show_users'
  get 'app/views/login/index.html.erb', to: 'login#index', as: 'login'
  get 'app/views/home/index.html.erb', to: 'home#index', as: 'home'
  get 'app/views/results/index.html.erb', to: 'results#index', as: 'results'
  get 'app/views/advancedsearch/index.html.erb', to: 'advancedsearch#index', as: 'advancedsearch'
  get 'app/views/browsingsearch/index.html.erb', to: 'browsingsearch#index', as: 'browsingsearch'
  get 'app/views/calendar/index.html.erb', to: 'calendar#index', as: 'calendar'
  get 'app/views/calendar_bookings/index.html.erb', to: 'calendar_bookings#index', as: 'calendar_bookings'
  get 'app/views/dailyreservations/index.html.erb', to: 'dailyreservations#index', as: 'dailyreservations'
  get 'app/views/calendar/show.html.erb', to: 'calendar#show', as: 'show_calendar'

  get    '/bright',  to: 'bright#index'
  get    '/rdmc',    to: 'rdmc#index'
  get    '/results',    to: 'results#index'

  get    '/bright',   to: 'bright#index'
  get    '/rdmc',   to: 'rdmc#index'
  get    '/add',    to: 'add#index'
  post   '/add',     to: 'rooms#create'
  get    '/delete',       to: 'delete#index'
  get    '/home',       to: 'home#index'
    
    
    
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create', as: 'login_path'
  get    '/create',  to: 'users#new'
  post   '/create',  to: 'users#create', as: 'users_path'
  delete '/logout',  to: 'sessions#destroy'
  delete '/user', to: 'users#destroy'

   resources :home
   resources :login
   resources :advancedsearch
   resources :results
   resources :browsingsearch
   resources :users, :bookings, :rooms
   resources :sessions
   resources :calendar
   resources :calendar_bookings
   
   get "*path", to: redirect('/')
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      @current_user = User.find(session[:user_id])
      @current_time = DateTime.now
      if @current_user[:usertype] == "Admin"
        @current_bookings = Booking.where("time_end  > ?", DateTime.now)
        @history_bookings = Booking.where("time_end  < ?", DateTime.now)
      else
        @current_bookings = Booking.where(:booker_id => session[:user_id]).where("time_end  > ?", DateTime.now)
        @history_bookings = Booking.where(:booker_id => session[:user_id]).where("time_end  < ?", DateTime.now)
      end
    end
    
    def params
      @params
    end
    
   render json:{data: 'index', status: 200, message: "go home" }
   
    before_action :validate_access 

private 
  def validate_access 
      unless logged_in?
        redirect_to root_path
      end 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE HTML>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="R^2">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <title>R^2 home</title>
    </head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    
    <body>
        <%= render './layouts/nav.html.erb' %>
        <center>
        <div class="container" style="background-color: green">
            <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>"><%= value %></div>
            <% end %>
            <%= yield %>
          </div>
       </center>
        <h2>Welcome back <%= current_user_name %>!</h2>
        
      <div class = "row">  
        <div class = "column left">

            <center>
             
           
              <h1>My Reservations</h1>
              <% if @current_bookings.length != 0 %>
                  <table width= 90% style ="display: block;" height=200px>
                  <tr>
                    <% if @current_user[:usertype] == "Admin" %>
                    <th>Booker</th>
                    <% end %>
                    <th>Building</th>
                    <th>Room Number</th>
                    <th>Room Type</th>
                    <th>Reason</th>
                    <th>Operate Start</th>
                    <th>Operate End</th>
                  </tr>
                  <% @current_bookings.each do |booking| %>
                     <tr>
                      <% if @current_user[:usertype] == "Admin" %>
                          <td><%= User.find(booking.booker_id).name %></td>
                      <% end %>  
                      <td><%= Room.find(booking.room_id).building_name %></td>
                      <td><%= Room.find(booking.room_id).room_id %></td>
                      <td><%= Room.find(booking.room_id).roomtype %></td>
                      <td><%= booking.reason %></td>
                      <td><%= booking.time_start.strftime("%b %d %Y, %-l.%M%P") %></td>
                      <td><%= booking.time_end.strftime("%b %d %Y, %-l.%M%P") %></td>
                      <td><%= link_to "Edit", edit_booking_path(booking) %></td>
                      <td><%= link_to "Delete", booking , :method => :delete, data: { confirm: 'Are you sure you want to cancel your booking?' } %></td>
                     </tr>
                  <% end %>
                </table>
                
              <% else %>
                <p>No reservations.</p>
              <% end %>
            
            
             
            
            </center>


            
          <!----------------------HISTORY BUTTON -------------------------------------------->
         
            <center>
              <button class ="btn" onclick ="myFunction()">Show History</button>
              
              
                 <th><% @current_date.to_s %></th>
            
                 <% if @history_bookings != nil %>
                      <h1 id= "history1" style ="display: none;">My History</h1>
                      <table id="history" width= 90% style ="display: none;" height=300px>
                      <tr>
                        <% if @current_user[:usertype] == "Admin" %>
                        <th>Booker</th>
                        <% end %> 
                        <th>Building</th>
                        <th>Room Number</th>
                        <th>Room Type</th>
                        <th>Reason</th>
                        <th>Operate Start</th>
                        <th>Operate End</th>
                      </tr>
                      <% @history_bookings.each do |booking| %>
                         <tr>
                          <% if @current_user[:usertype] == "Admin" %>
                            <td><%= User.find(booking.booker_id).name %></td>
                          <% end %>  
                          <td><%= Room.find(booking.room_id).building_name %></td>
                          <td><%= Room.find(booking.room_id).room_id %></td>
                          <td><%= Room.find(booking.room_id).roomtype %></td>
                          <td><%= booking.reason %></td>
                          <td><%= booking.time_start.strftime("%b %d %Y, %-l.%M%P") %></td>
                          <td><%= booking.time_end.strftime("%b %d %Y, %-l.%M%P") %></td>
                          
                         </tr>
                      <% end %>
                  </table>               
                 
                 <% else %>
                  <h1 style = "display: none;">No reservations.</h1>
                <% end %>
                         
          </center>
      

            </center>
  
          
        </div>
        
       
          <div class = "column right">
             <%= link_to "Make New Booking", new_booking_path, :class => "btn" %>
             <%= link_to "Calendar View", calendar_path, :class => "btn" %>
             <%if current_user_name == "Admin"%>
               <%=link_to'<button class = "btn" title = "Add Room" type = "button"> Add Room </button> '.html_safe, add_path%>
               <%=link_to'<button class = "btn" title = "Delete Room" type = "button"> Delete Room </button> '.html_safe, delete_path%>
                <%=link_to'<button class = "btn" title = "View Users" type = "button"> View Users </button> '.html_safe, show_users_path%>
               <% end %>
             <% else %>
            
          </div>
       
      </div>
        <div class="container">
          <%= debug(params) if Rails.env.development? %>
        </div>
        
         <br><br>
      
    </body>
    
     
    
<!-----------------------------------------JAVASCRIPT -------------------------------------> 
<script>
function myFunction() {
  var x = document.getElementById("history");
  var y = document.getElementById("history1");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
  if (y.style.display === "none") {
    y.style.display = "block";
  } else {
    y.style.display = "none";
  }
};
</script>
   
</html>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>