config/routes.rb
Rails.application.routes.draw do


  get 'booking/index'
# For styled pages
  root 'sessions#new'

  get 'sessions/new'
  get 'app/views/users/new.html.erb', to: 'users#new', as: 'new_user'
  get 'app/views/users/index.html.erb', to: 'users#index', as: 'show_users'
  get 'app/views/login/index.html.erb', to: 'login#index', as: 'login'
  get 'app/views/home/index.html.erb', to: 'home#index', as: 'home'
  get 'app/views/results/index.html.erb', to: 'results#index', as: 'results'
  get 'app/views/advancedsearch/index.html.erb', to: 'advancedsearch#index', as: 'advancedsearch'
  get 'app/views/browsingsearch/index.html.erb', to: 'browsingsearch#index', as: 'browsingsearch'
  get 'app/views/calendar/index.html.erb', to: 'calendar#index', as: 'calendar'
  get 'app/views/calendar_bookings/index.html.erb', to: 'calendar_bookings#index', as: 'calendar_bookings'
  get 'app/views/dailyreservations/index.html.erb', to: 'dailyreservations#index', as: 'dailyreservations'
  get 'app/views/calendar/show.html.erb', to: 'calendar#show', as: 'show_calendar'

  get    '/bright',  to: 'bright#index'
  get    '/rdmc',    to: 'rdmc#index'
  get    '/results',    to: 'results#index'

  get    '/bright',   to: 'bright#index'
  get    '/rdmc',   to: 'rdmc#index'
  get    '/add',    to: 'add#index'
  post   '/add',     to: 'rooms#create'
  get    '/delete',       to: 'delete#index'
  get    '/home',       to: 'home#index'
    
    
    
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create', as: 'login_path'
  get    '/create',  to: 'users#new'
  post   '/create',  to: 'users#create', as: 'users_path'
  delete '/logout',  to: 'sessions#destroy'
  delete '/user', to: 'users#destroy'

   resources :home
   resources :login
   resources :advancedsearch
   resources :results
   resources :browsingsearch
   resources :users, :bookings, :rooms
   resources :sessions
   resources :calendar
   resources :calendar_bookings
   
   get "*path", to: redirect('/')
end

app/models/room.rb
class Room < ActiveRecord::Base
    include Filterable
    validates :building_name, presence: true
    validates_uniqueness_of :room_id, :scope => :building_name
    validates :room_id, presence: true
    
    after_initialize :set_defaults, unless: :persisted?
    # The set_defaults will only work if the object is new
   
    def set_defaults
        self.booked  ||= false if self.booker.nil?
        self.booker = "---" if self.booker.nil?
    end
    
    scope :building_name, -> (building_name) { where building_name: building_name }
    scope :roomtype, -> (roomtype) { where roomtype: roomtype }
    scope :numpeople, -> (numpeople) { where numpeople: numpeople }
    scope :arrangement, -> (arrangement) { where arrangement: arrangement }
    scope :tech, -> (tech) { where tech: tech }
    
#   scope :starts_with, -> (name) { where("name like ?", "#{name}%")}
end
### make delete in here 

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
before_action :validate_access 

  def room_params
    params.require(:room).permit(:room_id, :roomtype, :building_name, :tech, :arrangement, :numpeople, :operate_start, :operate_end)
  end

  def show
    url = params[:current_page]
    puts "URL"
    puts url
    id = params[:id] # retrieve Room ID from URI route
    @room_exist = Room.where(:id => params[:id]).count
    if @room_exist > 0
      @room = Room.find(id) # look up Room by unique ID
      # will render app/views/Rooms/show.<extension> by default
    elsif url.include?('bright')
      redirect_to bright_path
    elsif url.include?('rdmc')
      redirect_to rdmc_path
    else
      redirect_to rooms_path
    end
  end

  def index
    @rooms = Room.all
  end

  def new
    #attr_accessor :building_name, :room_id, :roomtype, :description, :booked, :booker, :operate_start, :operate_end
    # def initialize(attributes = {})
    #   @building_name  = attributes[:building_name]
    #   @room_id = attributes[:room_id]
    #   @roomtype = attributes[:roomtype]
    #   @description = attributes[:description]
    #   @booked = attributes[:booked]
    #   @booker = attributes[:booker]
    #   @operate_start = attributes[:operate_start]
    #   @operate_end = attributes[:operate_end]
      
    # end
  end

  def create
    @room = Room.create!(building_name: params[:room][:building_name], 
    room_id: params[:Roomid], tech: params[:room][:tech],
    roomtype: params[:room][:roomtype], numpeople: params[:room][:numpeople],
    arrangement: params[:room][:arrangement], operate_start: params[:room][:operate_start].to_time,
    operate_end: params[:room][:operate_end].to_time, description: params[:room][:description])
    
    #flash[:notice] = "#{@room.building_name} #{@room.room_id} was successfully created."
    redirect_to rooms_path
  end

  def edit
    @room = Room.find params[:id]
  end

  def update
    @room = Room.find params[:id]
    @room.update_attributes!(room_params)
    redirect_to rooms_path
  end

  def destroy
    @HasBookings = Booking.where(:id => params[:id]).count
    if(@HasBookings > 0)
    if Booking.find(params[:id])
      @booking = Booking.find(params[:id])
      @building_name = @booking.building_name
      @room_number = Room.find(Booking.find(params[:id]).room_id).room_id
      @room_id = Booking.find(params[:id]).room_id
      
      @Initial_Bookings = Booking.where(:building_name => @building_name, :room_id => @room_id).count
      
      @Bookings = Booking.where(:building_name => @building_name, :room_id => @room_id)
      
      @Bookings.each do |booking|
        booking.destroy
      end
    end 
  end
    
    @Updated_Bookings = Booking.where(:building_name => @building_name, :room_id => @room_id).count
      #flash[:notice] = "Reservation are influenced"
    
      @Room = Room.find(params[:id])
      @Room.destroy
      #flash[:notice] = "No reservation are influenced"
  
    redirect_to delete_path
  end
  
private 
  def validate_access 
      unless logged_in?
        redirect_to root_path
      end 
  end

end

app/views/rooms/edit.html.erb
<!DOCTYPE HTML>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="R^2">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <title>R^2 browsing search</title>
    </head>
    
    <body>
      <%= render './layouts/nav.html.erb' %>
      <main>
        <fieldset id="editroom">
          
<legend>Edit Room</legend>

       <%= form_for @room, :url => {:action => "update", :id => @room}, 
        html:{method:'put'} do |f| %>
        
          <label>Building Name</label>
          <%= f.text_field :building_name %>
        
         <label>Room Number</label>  
         <%= f.text_field :room_id %>
          
          <label>Room Type</label>
          <%= f.collection_select :roomtype,
          Room.select('DISTINCT roomtype'),
          :roomtype, :roomtype, :required => true  %>
          
          <br>
          
          <label>Technology</label>
          <%= f.collection_select :tech,
          Room.select('DISTINCT tech'),
          :tech, :tech, :required => true  %>
          
          <br>
          
          <label>Arrangement</label>
          <%= f.collection_select :arrangement,
          Room.select('DISTINCT arrangement'),
          :arrangement, :arrangement, :required => true  %>
          
          <br>
          
          <label>Number of People</label>
          <%= f.collection_select :numpeople,
          Room.select('DISTINCT numpeople'),
          :numpeople, :numpeople, :required => true  %>
          
          <br>
          
          
          <%= f.submit "Edit" %>
        <% end %>
          
          <%= link_to 'Back', :back, :class => "btn" %>
        </fieldset>
      </main>
    </body>
    <div class="container">
      <%= debug(params) if Rails.env.development? %>
  </div>
</html>

app/views/rooms/index.html.erb
<%= render './layouts/nav.html.erb' %>
<h1>All Rooms</h1>
<table>
  <tr>
    <th>Building Name</th>
    <th>Room ID</th>
    <th>Room Type</th>
    <th>Operate Start</th>
    <th>Operate End</th>
    <th>Technology</th>
    <th>Arrangment</th>
    <th>Number of People</th>
    
  </tr>

  <% @rooms.each do |room| %>
    <tr>
      <td><%= room.building_name %></td>
      <td><%= room.room_id %></td>
      <td><%= room.roomtype %></td>
      <td><%= (room.operate_start + 6.hours).strftime("%k:%M") %></td>
      <td><%= (room.operate_end + 6.hours).strftime("%k:%M") %></td>
      <td><%= room.tech %></td>
      <td><%= room.arrangement%> </td>
      <td><%= room.numpeople%> </td>
      <% if @current_user = User.find(session[:user_id]).usertype == "Admin" %>
      <td><%= link_to "Edit",edit_room_path(room)  %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', :back, :class => "btn" %>

app/views/rooms/show.html.erb
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="R^2">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <title>R^2 browsing search</title>
    </head>
    <%= render './layouts/nav.html.erb' %>
    <% params.inspect %>
    <body>
      
        <div class ="room_title_container">
          <legend>More details about <%= @room.building_name %> Room #<%= @room.room_id %></legend>
        </div>
        <div class="room_details_container">
        <fieldset class="detail_area">
          <legend>Room Type</legend>
          <p><%= @room.roomtype %></p>
          <p>Able to accomodate: <%= @room.numpeople%> people</p>
        </fieldset>
        
        <fieldset class="detail_area">
          <legend>Operating Hours</legend>
          <p>Open at: <%= @room.operate_start.strftime("%k:%M") %></p>
          <p>Close at: <%= @room.operate_end.strftime("%k:%M") %></p>
        </fieldset>
        
        <fieldset class="detail_area">
          <legend>Facilities available</legend>  
          <p>Technology: <%= @room.tech %></p>
          <p>Arrangement: <%= @room.arrangement%> </p>
        </fieldset>
        
       
      </div>
    </body>
    
    <%= link_to 'Back', :back, :class => "btn" %>
</html>